/*
Welcome to the first exercise of this unit! In this task, you will learn how to change the port on which your Spring Boot application is running. By default, a Spring Boot application runs on port 8080. You will modify this configuration to change the port to 8081.

Open your src/main/resources/application.properties file.

Add the following line to the application.properties file:

.properties
server.port=8081
Start your application using the gradle bootRun command. During this process, you might see a progress indicator in the terminal that looks something like this: <==========---> 80% EXECUTING [6m 17s]. This indicates that Gradle is executing tasks and provides a visual representation of the progress and elapsed time. Since the Spring Boot application is a server that continues to run, this indicator will typically stay at 80% to show that the server is still executing and available.

In the logs you should see the messages which indicate that your app is running on port 8081 instead of default 8080:

2024-08-16T15:21:30.068Z  INFO 4984 --- [spring-boot-intro] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8081 (http)
2024-08-16T15:21:30.753Z  INFO 4984 --- [spring-boot-intro] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8081 (http) with context path ''
Note:
If you already have the application running (for example, from a previous gradle bootRun), make sure to stop it (press Ctrl+C in the terminal) before running the tests or starting the application again. Otherwise, you may encounter an error that the port is already in use.

Click Run to execute tests and then click Submit to proceed to the next task.
*/
spring.application.name=spring-boot-intro
server.port=8081